pool:
  name: Azure Pipelines
  demands:
    - npm
    - msbuild
    - MSBuild
    - Xamarin.Android
    - JDK

variables:
  incrementVersionCode: 'true'

steps:
  - task: qetza.replacetokens.replacetokens-task.replacetokens@3
    displayName: 'Replace tokens in **/GlobalConstants.cs **/TestSecrets.cs'
    inputs:
      targetFiles: |
        **/GlobalConstants.cs
        **/TestSecrets.cs
      actionOnMissing: fail

  - bash: |
      URL="https://bmm-api.brunstad.org/AppVersion/AndroidVersionCode"

      VERSIONCODE=$(curl -k --user $(bmmApiCredentials) $URL)

      echo "Receive version: $((VERSIONCODE))"

      echo "##vso[task.setvariable variable=VersionCode]$((VERSIONCODE))"
    displayName: 'Get  VersionCode'

  - bash: |
      let VERSIONCODE=++VERSIONCODE
      
      echo "New version set to: $((VERSIONCODE))"
      
      echo "##vso[task.setvariable variable=VersionCode]$((VERSIONCODE))"
    displayName: 'Increment VersionCode'

  - bash: |
      url="https://bmm-api.brunstad.org/AppVersion/AndroidVersionInfo"
  
      versionInfo=$(curl -k --user $(bmmApiCredentials) $url)
  
      echo "Receive version info: $versionInfo"
      echo "##vso[task.setvariable variable=VersionInfo]$versionInfo"
    displayName: 'Get version info'