pool:
  name: Azure Pipelines
  demands:
    - npm
    - msbuild
    - MSBuild
    - Xamarin.Android
    - JDK

variables:
  incrementVersionCode: 'true'

steps:
  - task: qetza.replacetokens.replacetokens-task.replacetokens@3
    displayName: 'Replace tokens in **/GlobalConstants.cs **/TestSecrets.cs'
    inputs:
      targetFiles: |
        **/GlobalConstants.cs
        **/TestSecrets.cs
      actionOnMissing: fail

  - bash: |
      URL="https://bmm-api.brunstad.org/AppVersion/AndroidVersionCode"

      VERSIONCODE=$(curl -k --user $(bmmApiCredentials) $URL)

      echo "Receive version: $((VERSIONCODE))"

      echo "##vso[task.setvariable variable=VersionCode]$((VERSIONCODE))"
    displayName: 'Get  VersionCode'

  - bash: |
      let VERSIONCODE=++VERSIONCODE
      
      echo "New version set to: $((VERSIONCODE))"
      
      echo "##vso[task.setvariable variable=VersionCode]$((VERSIONCODE))"
    displayName: 'Increment VersionCode'

  - bash: |
      url="https://bmm-api.brunstad.org/AppVersion/AndroidVersionInfo"
  
      versionInfo=$(curl -k --user $(bmmApiCredentials) $url)
  
      echo "Receive version info: $versionInfo"
      echo "##vso[task.setvariable variable=VersionInfo]$versionInfo"
    displayName: 'Get version info'

  - task: Bash@3
    inputs:
      filePath: 'version-info.sh'
    displayName: 'Construct new version number'

  - task: CdiscountAlm.rest-call-build-task.custom-build-task.restCallBuildTask@0
    displayName: 'Rest call PUT AppVersion/AndroidVersionCode'
    inputs:
      webserviceEndpoint: 'BMM Api (Basic Auth)'
      relativeUrl: AppVersion/AndroidVersionCode
      httpVerb: PUT
      body: '$(VersionCode)'
      headers: |
        {
          "Content-Length": "6",
          "Authorization": "$(bmmApiBasicAuth)"
        }

  - task: CdiscountAlm.rest-call-build-task.custom-build-task.restCallBuildTask@0
    displayName: 'Rest call PUT AppVersion/AndroidVersionInfo'
    inputs:
      webserviceEndpoint: 'BMM Api (Basic Auth)'
      relativeUrl: AppVersion/AndroidVersionInfo
      httpVerb: PUT
      body: '$(VersionInfo_String)'
      headers: |
        {
          "Content-Length": "$(VersionInfo_Length)",
          "Authorization": "$(bmmApiBasicAuth)"
        }